<?xml version="1.0" encoding="utf-8"?>
<Database Name="SageFrame" Class="SettingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=braindignet;Initial Catalog=SageFrame;User ID=sa" SettingsObjectName="SageFrame.Common.Properties.Settings" SettingsPropertyName="SageFrameConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_SettingAdd" Method="sp_SettingAdd">
    <Parameter Name="SettingID" Parameter="settingID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NText" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_SettingUpdate" Method="sp_SettingUpdate">
    <Parameter Name="SettingID" Parameter="settingID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NText" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_SettingBySettingID" Method="sp_SettingBySettingID">
    <Parameter Name="SettingID" Parameter="settingID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_SettingBySettingIDResult">
      <Column Name="SettingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SettingDelete" Method="sp_SettingDelete">
    <Parameter Name="SettingID" Parameter="settingID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_SettingList" Method="sp_SettingList">
    <ElementType Name="sp_SettingListResult">
      <Column Name="SettingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SettingPortalAdd" Method="sp_SettingPortalAdd">
    <Parameter Name="SettingPortal" Parameter="settingPortal" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="SettingID" Parameter="settingID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_SettingPortalAddUpdateList" Method="sp_SettingPortalAddUpdateList">
    <Parameter Name="strKeyes" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="strValues" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Return" Parameter="return" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_SettingPortalByPortalID" Method="sp_SettingPortalByPortalID">
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_SettingPortalByPortalIDResult">
      <Column Name="SettingPortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SettingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultValue" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SettingPortalBySettingID" Method="sp_SettingPortalBySettingID">
    <Parameter Name="SettingID" Parameter="settingID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_SettingPortalBySettingIDResult">
      <Column Name="SettingPortalID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SettingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DefaultValue" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SettingPortalDelete" Method="sp_SettingPortalDelete">
    <Parameter Name="SettingID" Parameter="settingID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_SettingPortalList" Method="sp_SettingPortalList">
    <ElementType Name="sp_SettingPortalListResult">
      <Column Name="SettingPortalID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SettingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SettingPortalUpdate" Method="sp_SettingPortalUpdate">
    <Parameter Name="SettingID" Parameter="settingID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>