<?xml version="1.0" encoding="utf-8"?>
<Database Name="sftemplating" Class="NewsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SUJANDOTNET;Initial Catalog=sftemplating;User ID=sa" SettingsObjectName="SageFrame.News.Properties.Settings" SettingsPropertyName="sftemplatingConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_NewsAddFromCategory" Method="sp_NewsAddFromCategory">
    <Parameter Name="NewsTypeID" Parameter="newsTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NewsCategoryID" Parameter="newsCategoryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NewsTitle" Parameter="newsTitle" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="NewsShortDescription" Parameter="newsShortDescription" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="NewsLongDescription" Parameter="newsLongDescription" Type="System.String" DbType="NText" />
    <Parameter Name="NewsDate" Parameter="newsDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AddedOn" Parameter="addedOn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewsGetbyNewsID" Method="sp_NewsGetbyNewsID">
    <Parameter Name="NewsID" Parameter="newsID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_NewsGetbyNewsIDResult">
      <Column Name="NewsID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewsCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewsTitle" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NewsShortDescription" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="NewsLongDescription" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_NewsLongDescriptionbyNewsID" Method="sp_NewsLongDescriptionbyNewsID">
    <Parameter Name="NewsID" Parameter="newsID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_NewsLongDescriptionbyNewsIDResult">
      <Column Name="NewsLongDescription" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_NewsType" Method="sp_NewsType">
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_NewsTypeResult">
      <Column Name="NewsTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsType" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_NewsDeletebyNewsID" Method="sp_NewsDeletebyNewsID">
    <Parameter Name="NewsID" Parameter="newsID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DeletedBy" Parameter="deletedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewsAllbyNewsID" Method="sp_NewsAllbyNewsID">
    <Parameter Name="NewsID" Parameter="newsID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_NewsAllbyNewsIDResult">
      <Column Name="NewsID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewsCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewsTitle" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NewsShortDescription" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="NewsLongDescription" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_NewsUpdatebyNewsID" Method="sp_NewsUpdatebyNewsID">
    <Parameter Name="NewsID" Parameter="newsID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NewsTypeID" Parameter="newsTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NewsCategoryID" Parameter="newsCategoryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NewsTitle" Parameter="newsTitle" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="NewsShortDescription" Parameter="newsShortDescription" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="NewsLongDescription" Parameter="newsLongDescription" Type="System.String" DbType="NText" />
    <Parameter Name="NewsDate" Parameter="newsDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsModified" Parameter="isModified" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UpdatedBy" Parameter="updatedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewsCategoryAdd" Method="sp_NewsCategoryAdd">
    <Parameter Name="NewsCategoryID" Parameter="newsCategoryID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="NewsCategory" Parameter="newsCategory" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="NewsCategoryDescription" Parameter="newsCategoryDescription" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="ImageID" Parameter="imageID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AddedOn" Parameter="addedOn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AddedBy" Parameter="addedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewsCategoryDelete" Method="sp_NewsCategoryDelete">
    <Parameter Name="NewsCategoryID" Parameter="newsCategoryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DeletedBy" Parameter="deletedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewsCategoryUpdate" Method="sp_NewsCategoryUpdate">
    <Parameter Name="NewsCategoryID" Parameter="newsCategoryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NewsCategory" Parameter="newsCategory" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="NewsCategoryDescription" Parameter="newsCategoryDescription" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="ImageID" Parameter="imageID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsModified" Parameter="isModified" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UpdatedOn" Parameter="updatedOn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UpdatedBy" Parameter="updatedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewsCheckUniqueNewsCategoryName" Method="sp_NewsCheckUniqueNewsCategoryName">
    <Parameter Name="NewsCategoryID" Parameter="newsCategoryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NewsCategory" Parameter="newsCategory" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="isEdit" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="categoryCount" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewsCategoryImageAdd" Method="sp_NewsCategoryImageAdd">
    <Parameter Name="ImageExtension" Parameter="imageExtension" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="LargeImagePath" Parameter="largeImagePath" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="MediumImagePath" Parameter="mediumImagePath" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="SmallImagePath" Parameter="smallImagePath" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AddedBy" Parameter="addedBy" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="ImageID" Parameter="imageID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewsCategoryImageUpdate" Method="sp_NewsCategoryImageUpdate">
    <Parameter Name="NewsCategoryID" Parameter="newsCategoryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ImageExtension" Parameter="imageExtension" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="LargeImagePath" Parameter="largeImagePath" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="MediumImagePath" Parameter="mediumImagePath" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="SmallImagePath" Parameter="smallImagePath" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AddedBy" Parameter="addedBy" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="ImageID" Parameter="imageID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewsCategoryByNewsCategoryID" Method="sp_NewsCategoryByNewsCategoryID">
    <Parameter Name="NewsCategoryID" Parameter="newsCategoryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_NewsCategoryByNewsCategoryIDResult">
      <Column Name="NewsCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsCategory" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="NewsCategoryDescription" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ImageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="SmallImagePath" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ImageExtension" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_NewsSettingUpdate" Method="sp_NewsSettingUpdate">
    <Parameter Name="NewsSettingValueID" Parameter="newsSettingValueID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="UserModuleID" Parameter="userModuleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SettingKey" Parameter="settingKey" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="SettingValue" Parameter="settingValue" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UpdatedBy" Parameter="updatedBy" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="AddedBy" Parameter="addedBy" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewsSettingGetAll" Method="sp_NewsSettingGetAll">
    <Parameter Name="UserModuleID" Parameter="userModuleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_NewsSettingGetAllResult">
      <Column Name="NewsSettingValueID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserModuleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SettingKey" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="SettingValue" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_CheckUserModulePermissionByPermissionKey" Method="sp_CheckUserModulePermissionByPermissionKey">
    <Parameter Name="PermissionKey" Parameter="permissionKey" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="UserModuleID" Parameter="userModuleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewsList" Method="sp_NewsList">
    <Parameter Name="UserModuleID" Parameter="userModuleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_NewsListResult">
      <Column Name="NewsID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewsCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewsTitle" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NewsShortDescription" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="NewsLongDescription" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_NewsCategoryCount" Method="sp_NewsCategoryCount">
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Option" Parameter="option" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Count" Parameter="count" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewsCategory" Method="sp_NewsCategory">
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="sp_NewsCategoryResult">
      <Column Name="NewsCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsCategory" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="NewsCategoryDescription" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ImageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="SmallImagePath" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="ImageExtension" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_NewsCategoryImageFoldersGet" Method="sp_NewsCategoryImageFoldersGet">
    <Parameter Name="NewsCategoryID" Parameter="newsCategoryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_NewsCategoryImageFoldersGetResult">
      <Column Name="ImageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImageExtension" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LargeImagePath" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="MediumImagePath" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="SmallImagePath" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_NewsView" Method="sp_NewsView">
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NewsCategoryID" Parameter="newsCategoryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="sp_NewsViewResult">
      <Column Name="NewsID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewsCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewsTitle" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NewsShortDescription" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="NewsLongDescription" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsModified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_NewsRSSList" Method="sp_NewsRSSList">
    <Parameter Name="UserModuleID" Parameter="userModuleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PortalID" Parameter="portalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NewsCount" Parameter="newsCount" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_NewsRSSListResult">
      <Column Name="NewsID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsTitle" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="NewsShortDescription" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="NewsLongDescription" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddedBy" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>