#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SageFrame.FeedBack
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SageFrame27")]
	public partial class FeedBackDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public FeedBackDataContext() : 
				base(global::SageFrame.FeedBack.Properties.Settings.Default.SageFrameConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FeedBackDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FeedBackDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FeedBackDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FeedBackDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FeedbackItemUpdate")]
		public int sp_FeedbackItemUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeedbackItemID", DbType="Int")] System.Nullable<int> feedbackItemID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeedbackItem", DbType="NVarChar(256)")] string feedbackItem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DisplayOrder", DbType="Int")] System.Nullable<int> displayOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsModified", DbType="Bit")] System.Nullable<bool> isModified, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UpdatedOn", DbType="DateTime")] System.Nullable<System.DateTime> updatedOn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddedBy", DbType="NVarChar(256)")] string addedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UpdatedBy", DbType="NVarChar(256)")] string updatedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), feedbackItemID, feedbackItem, displayOrder, isActive, isModified, updatedOn, portalID, addedBy, updatedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FeedBackAdd")]
		public int sp_FeedBackAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeedbackItemID", DbType="Int")] System.Nullable<int> feedbackItemID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeedbackItem", DbType="NVarChar(256)")] string feedbackItem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DisplayOrder", DbType="Int")] System.Nullable<int> displayOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsModified", DbType="Bit")] System.Nullable<bool> isModified, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddedOn", DbType="DateTime")] System.Nullable<System.DateTime> addedOn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddedBy", DbType="NVarChar(256)")] string addedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), feedbackItemID, feedbackItem, displayOrder, isActive, isModified, addedOn, portalID, addedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FeedbackItemAdd")]
		public int sp_FeedbackItemAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeedbackItem", DbType="NVarChar(256)")] string feedbackItem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FieldCaption", DbType="NVarChar(500)")] string fieldCaption, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DisplayOrder", DbType="Int")] System.Nullable<int> displayOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddedBy", DbType="NVarChar(256)")] string addedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), feedbackItem, fieldCaption, displayOrder, isActive, portalID, addedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FeedbackSettingGetAll")]
		public ISingleResult<sp_FeedbackSettingGetAllResult> sp_FeedbackSettingGetAll([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserModuleID", DbType="Int")] System.Nullable<int> userModuleID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userModuleID, portalID);
			return ((ISingleResult<sp_FeedbackSettingGetAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FeedbackSettingUpdate")]
		public int sp_FeedbackSettingUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeedbackSettingValueID", DbType="Int")] ref System.Nullable<int> feedbackSettingValueID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserModuleID", DbType="Int")] System.Nullable<int> userModuleID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SettingKey", DbType="NVarChar(256)")] string settingKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SettingValue", DbType="NVarChar(256)")] string settingValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UpdatedBy", DbType="NVarChar(256)")] string updatedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddedBy", DbType="NVarChar(256)")] string addedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), feedbackSettingValueID, userModuleID, settingKey, settingValue, isActive, portalID, updatedBy, addedBy);
			feedbackSettingValueID = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetListEntriesByNameParentKeyAndPortalID")]
		public ISingleResult<sp_GetListEntriesByNameParentKeyAndPortalIDResult> sp_GetListEntriesByNameParentKeyAndPortalID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ListName", DbType="NVarChar(50)")] string listName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentKey", DbType="NVarChar(150)")] string parentKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), listName, parentKey, portalID);
			return ((ISingleResult<sp_GetListEntriesByNameParentKeyAndPortalIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetListEntrybyNameAndID")]
		public ISingleResult<sp_GetListEntrybyNameAndIDResult> sp_GetListEntrybyNameAndID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ListName", DbType="NVarChar(50)")] string listName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryID", DbType="Int")] System.Nullable<int> entryID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), listName, entryID);
			return ((ISingleResult<sp_GetListEntrybyNameAndIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FeedbackFormAddandUpdate")]
		public int sp_FeedbackFormAddandUpdate(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormTitle", DbType="NVarChar(200)")] string formTitle, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormInfo", DbType="NVarChar(4000)")] string formInfo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(250)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermanentCountry", DbType="NVarChar(100)")] string permanentCountry, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermanentState", DbType="NVarChar(100)")] string permanentState, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermanentCity", DbType="NVarChar(100)")] string permanentCity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermanentZipCode", DbType="NVarChar(50)")] string permanentZipCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermanentPostCode", DbType="NVarChar(50)")] string permanentPostCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermanentAddress", DbType="NVarChar(256)")] string permanentAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemporaryCountry", DbType="NVarChar(100)")] string temporaryCountry, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemporaryState", DbType="NVarChar(100)")] string temporaryState, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemporaryCity", DbType="NVarChar(100)")] string temporaryCity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemporaryZipCode", DbType="NVarChar(50)")] string temporaryZipCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemporaryPostCode", DbType="NVarChar(50)")] string temporaryPostCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemporaryAddress", DbType="NVarChar(256)")] string temporaryAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email1", DbType="NVarChar(256)")] string email1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email2", DbType="NVarChar(256)")] string email2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone1", DbType="NVarChar(100)")] string phone1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone2", DbType="NVarChar(100)")] string phone2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="NVarChar(100)")] string mobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="NVarChar(500)")] string company, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Website", DbType="NVarChar(500)")] string website, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="NVarChar(4000)")] string message, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Attachment", DbType="NVarChar(256)")] string attachment, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddedOn", DbType="DateTime")] System.Nullable<System.DateTime> addedOn, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddedBy", DbType="NVarChar(256)")] string addedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), formTitle, formInfo, name, permanentCountry, permanentState, permanentCity, permanentZipCode, permanentPostCode, permanentAddress, temporaryCountry, temporaryState, temporaryCity, temporaryZipCode, temporaryPostCode, temporaryAddress, email1, email2, phone1, phone2, mobile, company, website, message, attachment, isActive, addedOn, portalID, addedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FeedbackGet")]
		public ISingleResult<sp_FeedbackGetResult> sp_FeedbackGet()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_FeedbackGetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FeedbackDeletebyFeedbackID")]
		public int sp_FeedbackDeletebyFeedbackID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeedbackID", DbType="Int")] System.Nullable<int> feedbackID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeletedBy", DbType="NVarChar(256)")] string deletedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), feedbackID, portalID, deletedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FeedbackFormAdd")]
		public int sp_FeedbackFormAdd(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormTitle", DbType="NVarChar(200)")] string formTitle, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormInfo", DbType="NVarChar(4000)")] string formInfo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(256)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermanentCountry", DbType="NVarChar(100)")] string permanentCountry, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermanentState", DbType="NVarChar(100)")] string permanentState, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermanentCity", DbType="NVarChar(100)")] string permanentCity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermanentZipCode", DbType="NVarChar(50)")] string permanentZipCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermanentPostCode", DbType="NVarChar(50)")] string permanentPostCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermanentAddress", DbType="NVarChar(256)")] string permanentAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemporaryCountry", DbType="NVarChar(100)")] string temporaryCountry, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemporaryState", DbType="NVarChar(100)")] string temporaryState, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemporaryCity", DbType="NVarChar(100)")] string temporaryCity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemporaryZipCode", DbType="NVarChar(50)")] string temporaryZipCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemporaryPostCode", DbType="NVarChar(50)")] string temporaryPostCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemporaryAddress", DbType="NVarChar(256)")] string temporaryAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email1", DbType="NVarChar(256)")] string email1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email2", DbType="NVarChar(256)")] string email2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone1", DbType="NVarChar(100)")] string phone1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone2", DbType="NVarChar(100)")] string phone2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="NVarChar(100)")] string mobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="NVarChar(500)")] string company, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Website", DbType="NVarChar(500)")] string website, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="NVarChar(4000)")] string message, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Attachment", DbType="NVarChar(256)")] string attachment, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddedOn", DbType="DateTime")] System.Nullable<System.DateTime> addedOn, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddedBy", DbType="NVarChar(256)")] string addedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), formTitle, formInfo, name, permanentCountry, permanentState, permanentCity, permanentZipCode, permanentPostCode, permanentAddress, temporaryCountry, temporaryState, temporaryCity, temporaryZipCode, temporaryPostCode, temporaryAddress, email1, email2, phone1, phone2, mobile, company, website, message, attachment, isActive, addedOn, portalID, addedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FeedbackGetList")]
		public int sp_FeedbackGetList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(256)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), portalID, username);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertUpdateFeedbackItems")]
		public int sp_InsertUpdateFeedbackItems([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeedbackItems", DbType="NVarChar(4000)")] string feedbackItems, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FieldCaptions", DbType="NVarChar(4000)")] string fieldCaptions, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DisplayOrders", DbType="NVarChar(4000)")] string displayOrders, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActives", DbType="NVarChar(4000)")] string isActives, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(256)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CultureName", DbType="NVarChar(256)")] string cultureName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), feedbackItems, fieldCaptions, displayOrders, isActives, username, cultureName, portalID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FeedbackItemGet")]
		public ISingleResult<sp_FeedbackItemGetResult> sp_FeedbackItemGet([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CultureName", DbType="NVarChar(256)")] string cultureName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), portalID, cultureName);
			return ((ISingleResult<sp_FeedbackItemGetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FeedbackSettingValueList")]
		public ISingleResult<sp_FeedbackSettingValueListResult> sp_FeedbackSettingValueList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), portalID);
			return ((ISingleResult<sp_FeedbackSettingValueListResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_FeedbackSettingGetAllResult
	{
		
		private int _FeedbackSettingValueID;
		
		private System.Nullable<int> _UserModuleID;
		
		private string _SettingKey;
		
		private string _SettingValue;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<bool> _IsModified;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<int> _PortalID;
		
		private string _AddedBy;
		
		private string _UpdatedBy;
		
		private string _DeletedBy;
		
		public sp_FeedbackSettingGetAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedbackSettingValueID", DbType="Int NOT NULL")]
		public int FeedbackSettingValueID
		{
			get
			{
				return this._FeedbackSettingValueID;
			}
			set
			{
				if ((this._FeedbackSettingValueID != value))
				{
					this._FeedbackSettingValueID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserModuleID", DbType="Int")]
		public System.Nullable<int> UserModuleID
		{
			get
			{
				return this._UserModuleID;
			}
			set
			{
				if ((this._UserModuleID != value))
				{
					this._UserModuleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettingKey", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string SettingKey
		{
			get
			{
				return this._SettingKey;
			}
			set
			{
				if ((this._SettingKey != value))
				{
					this._SettingKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettingValue", DbType="NVarChar(256)")]
		public string SettingValue
		{
			get
			{
				return this._SettingValue;
			}
			set
			{
				if ((this._SettingValue != value))
				{
					this._SettingValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsModified", DbType="Bit")]
		public System.Nullable<bool> IsModified
		{
			get
			{
				return this._IsModified;
			}
			set
			{
				if ((this._IsModified != value))
				{
					this._IsModified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this._DeletedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="NVarChar(256)")]
		public string DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this._DeletedBy = value;
				}
			}
		}
	}
	
	public partial class sp_GetListEntriesByNameParentKeyAndPortalIDResult
	{
		
		private int _EntryID;
		
		private string _ListName;
		
		private string _Value;
		
		private string _Text;
		
		private int _Level;
		
		private string _CurrencyCode;
		
		private string _DisplayLocale;
		
		private int _DisplayOrder;
		
		private int _DefinitionID;
		
		private int _ParentID;
		
		private string _Description;
		
		private int _PortalID;
		
		private bool _SystemList;
		
		private string _ParentKey;
		
		private string _Parent;
		
		private string _ParentList;
		
		private System.Nullable<int> _MaxSortOrder;
		
		private System.Nullable<int> _EntryCount;
		
		private System.Nullable<int> _HasChildren;
		
		private System.Nullable<bool> _IsActive;
		
		private string _AddedBy;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private string _UpdatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		public sp_GetListEntriesByNameParentKeyAndPortalIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryID", DbType="Int NOT NULL")]
		public int EntryID
		{
			get
			{
				return this._EntryID;
			}
			set
			{
				if ((this._EntryID != value))
				{
					this._EntryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ListName
		{
			get
			{
				return this._ListName;
			}
			set
			{
				if ((this._ListName != value))
				{
					this._ListName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int NOT NULL")]
		public int Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyCode", DbType="NVarChar(50)")]
		public string CurrencyCode
		{
			get
			{
				return this._CurrencyCode;
			}
			set
			{
				if ((this._CurrencyCode != value))
				{
					this._CurrencyCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayLocale", DbType="NVarChar(50)")]
		public string DisplayLocale
		{
			get
			{
				return this._DisplayLocale;
			}
			set
			{
				if ((this._DisplayLocale != value))
				{
					this._DisplayLocale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayOrder", DbType="Int NOT NULL")]
		public int DisplayOrder
		{
			get
			{
				return this._DisplayOrder;
			}
			set
			{
				if ((this._DisplayOrder != value))
				{
					this._DisplayOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefinitionID", DbType="Int NOT NULL")]
		public int DefinitionID
		{
			get
			{
				return this._DefinitionID;
			}
			set
			{
				if ((this._DefinitionID != value))
				{
					this._DefinitionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int NOT NULL")]
		public int ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemList", DbType="Bit NOT NULL")]
		public bool SystemList
		{
			get
			{
				return this._SystemList;
			}
			set
			{
				if ((this._SystemList != value))
				{
					this._SystemList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentKey", DbType="NVarChar(2000)")]
		public string ParentKey
		{
			get
			{
				return this._ParentKey;
			}
			set
			{
				if ((this._ParentKey != value))
				{
					this._ParentKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent", DbType="NVarChar(2000)")]
		public string Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this._Parent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentList", DbType="NVarChar(2000)")]
		public string ParentList
		{
			get
			{
				return this._ParentList;
			}
			set
			{
				if ((this._ParentList != value))
				{
					this._ParentList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxSortOrder", DbType="Int")]
		public System.Nullable<int> MaxSortOrder
		{
			get
			{
				return this._MaxSortOrder;
			}
			set
			{
				if ((this._MaxSortOrder != value))
				{
					this._MaxSortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryCount", DbType="Int")]
		public System.Nullable<int> EntryCount
		{
			get
			{
				return this._EntryCount;
			}
			set
			{
				if ((this._EntryCount != value))
				{
					this._EntryCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasChildren", DbType="Int")]
		public System.Nullable<int> HasChildren
		{
			get
			{
				return this._HasChildren;
			}
			set
			{
				if ((this._HasChildren != value))
				{
					this._HasChildren = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
	}
	
	public partial class sp_GetListEntrybyNameAndIDResult
	{
		
		private int _EntryID;
		
		private string _ListName;
		
		private string _Value;
		
		private string _Text;
		
		private int _Level;
		
		private string _CurrencyCode;
		
		private string _DisplayLocale;
		
		private int _DisplayOrder;
		
		private int _DefinitionID;
		
		private int _ParentID;
		
		private string _Description;
		
		private int _PortalID;
		
		private bool _SystemList;
		
		private string _ParentKey;
		
		private string _Parent;
		
		private string _ParentList;
		
		private System.Nullable<int> _MaxSortOrder;
		
		private System.Nullable<int> _EntryCount;
		
		private System.Nullable<int> _HasChildren;
		
		private System.Nullable<bool> _IsActive;
		
		private string _AddedBy;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private string _UpdatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		public sp_GetListEntrybyNameAndIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryID", DbType="Int NOT NULL")]
		public int EntryID
		{
			get
			{
				return this._EntryID;
			}
			set
			{
				if ((this._EntryID != value))
				{
					this._EntryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ListName
		{
			get
			{
				return this._ListName;
			}
			set
			{
				if ((this._ListName != value))
				{
					this._ListName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int NOT NULL")]
		public int Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyCode", DbType="NVarChar(50)")]
		public string CurrencyCode
		{
			get
			{
				return this._CurrencyCode;
			}
			set
			{
				if ((this._CurrencyCode != value))
				{
					this._CurrencyCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayLocale", DbType="NVarChar(50)")]
		public string DisplayLocale
		{
			get
			{
				return this._DisplayLocale;
			}
			set
			{
				if ((this._DisplayLocale != value))
				{
					this._DisplayLocale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayOrder", DbType="Int NOT NULL")]
		public int DisplayOrder
		{
			get
			{
				return this._DisplayOrder;
			}
			set
			{
				if ((this._DisplayOrder != value))
				{
					this._DisplayOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefinitionID", DbType="Int NOT NULL")]
		public int DefinitionID
		{
			get
			{
				return this._DefinitionID;
			}
			set
			{
				if ((this._DefinitionID != value))
				{
					this._DefinitionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int NOT NULL")]
		public int ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemList", DbType="Bit NOT NULL")]
		public bool SystemList
		{
			get
			{
				return this._SystemList;
			}
			set
			{
				if ((this._SystemList != value))
				{
					this._SystemList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentKey", DbType="NVarChar(2000)")]
		public string ParentKey
		{
			get
			{
				return this._ParentKey;
			}
			set
			{
				if ((this._ParentKey != value))
				{
					this._ParentKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent", DbType="NVarChar(2000)")]
		public string Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this._Parent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentList", DbType="NVarChar(2000)")]
		public string ParentList
		{
			get
			{
				return this._ParentList;
			}
			set
			{
				if ((this._ParentList != value))
				{
					this._ParentList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxSortOrder", DbType="Int")]
		public System.Nullable<int> MaxSortOrder
		{
			get
			{
				return this._MaxSortOrder;
			}
			set
			{
				if ((this._MaxSortOrder != value))
				{
					this._MaxSortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryCount", DbType="Int")]
		public System.Nullable<int> EntryCount
		{
			get
			{
				return this._EntryCount;
			}
			set
			{
				if ((this._EntryCount != value))
				{
					this._EntryCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasChildren", DbType="Int")]
		public System.Nullable<int> HasChildren
		{
			get
			{
				return this._HasChildren;
			}
			set
			{
				if ((this._HasChildren != value))
				{
					this._HasChildren = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
	}
	
	public partial class sp_FeedbackGetResult
	{
		
		private string _FormTitle;
		
		private string _FormInfo;
		
		private string _Name;
		
		private string _PermanentCountry;
		
		private string _PermanentState;
		
		private string _PermanentCity;
		
		private string _PermanentZipCode;
		
		private string _PermanentPostCode;
		
		private string _PermanentAddress;
		
		private string _TemporaryCountry;
		
		private string _TemporaryState;
		
		private string _TemporaryCity;
		
		private string _TemporaryZipCode;
		
		private string _TemporaryPostCode;
		
		private string _TemporaryAddress;
		
		private string _Email1;
		
		private string _Email2;
		
		private string _Phone1;
		
		private string _Phone2;
		
		private string _Mobile;
		
		private string _Company;
		
		private string _Website;
		
		private string _Message;
		
		private string _Attachment;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<bool> _IsModified;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<int> _PortalID;
		
		private string _AddedBy;
		
		private string _UpdatedBy;
		
		private string _DeletedBy;
		
		public sp_FeedbackGetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormTitle", DbType="NVarChar(200)")]
		public string FormTitle
		{
			get
			{
				return this._FormTitle;
			}
			set
			{
				if ((this._FormTitle != value))
				{
					this._FormTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormInfo", DbType="NVarChar(4000)")]
		public string FormInfo
		{
			get
			{
				return this._FormInfo;
			}
			set
			{
				if ((this._FormInfo != value))
				{
					this._FormInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(256)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermanentCountry", DbType="NVarChar(100)")]
		public string PermanentCountry
		{
			get
			{
				return this._PermanentCountry;
			}
			set
			{
				if ((this._PermanentCountry != value))
				{
					this._PermanentCountry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermanentState", DbType="NVarChar(100)")]
		public string PermanentState
		{
			get
			{
				return this._PermanentState;
			}
			set
			{
				if ((this._PermanentState != value))
				{
					this._PermanentState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermanentCity", DbType="NVarChar(100)")]
		public string PermanentCity
		{
			get
			{
				return this._PermanentCity;
			}
			set
			{
				if ((this._PermanentCity != value))
				{
					this._PermanentCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermanentZipCode", DbType="NVarChar(50)")]
		public string PermanentZipCode
		{
			get
			{
				return this._PermanentZipCode;
			}
			set
			{
				if ((this._PermanentZipCode != value))
				{
					this._PermanentZipCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermanentPostCode", DbType="NVarChar(50)")]
		public string PermanentPostCode
		{
			get
			{
				return this._PermanentPostCode;
			}
			set
			{
				if ((this._PermanentPostCode != value))
				{
					this._PermanentPostCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermanentAddress", DbType="NVarChar(256)")]
		public string PermanentAddress
		{
			get
			{
				return this._PermanentAddress;
			}
			set
			{
				if ((this._PermanentAddress != value))
				{
					this._PermanentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemporaryCountry", DbType="NVarChar(100)")]
		public string TemporaryCountry
		{
			get
			{
				return this._TemporaryCountry;
			}
			set
			{
				if ((this._TemporaryCountry != value))
				{
					this._TemporaryCountry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemporaryState", DbType="NVarChar(100)")]
		public string TemporaryState
		{
			get
			{
				return this._TemporaryState;
			}
			set
			{
				if ((this._TemporaryState != value))
				{
					this._TemporaryState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemporaryCity", DbType="NVarChar(100)")]
		public string TemporaryCity
		{
			get
			{
				return this._TemporaryCity;
			}
			set
			{
				if ((this._TemporaryCity != value))
				{
					this._TemporaryCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemporaryZipCode", DbType="NVarChar(50)")]
		public string TemporaryZipCode
		{
			get
			{
				return this._TemporaryZipCode;
			}
			set
			{
				if ((this._TemporaryZipCode != value))
				{
					this._TemporaryZipCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemporaryPostCode", DbType="NVarChar(50)")]
		public string TemporaryPostCode
		{
			get
			{
				return this._TemporaryPostCode;
			}
			set
			{
				if ((this._TemporaryPostCode != value))
				{
					this._TemporaryPostCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemporaryAddress", DbType="NVarChar(256)")]
		public string TemporaryAddress
		{
			get
			{
				return this._TemporaryAddress;
			}
			set
			{
				if ((this._TemporaryAddress != value))
				{
					this._TemporaryAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email1", DbType="NVarChar(256)")]
		public string Email1
		{
			get
			{
				return this._Email1;
			}
			set
			{
				if ((this._Email1 != value))
				{
					this._Email1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email2", DbType="NVarChar(256)")]
		public string Email2
		{
			get
			{
				return this._Email2;
			}
			set
			{
				if ((this._Email2 != value))
				{
					this._Email2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone1", DbType="NVarChar(100)")]
		public string Phone1
		{
			get
			{
				return this._Phone1;
			}
			set
			{
				if ((this._Phone1 != value))
				{
					this._Phone1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2", DbType="NVarChar(100)")]
		public string Phone2
		{
			get
			{
				return this._Phone2;
			}
			set
			{
				if ((this._Phone2 != value))
				{
					this._Phone2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(100)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(500)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="NVarChar(500)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this._Website = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(4000)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attachment", DbType="NVarChar(256)")]
		public string Attachment
		{
			get
			{
				return this._Attachment;
			}
			set
			{
				if ((this._Attachment != value))
				{
					this._Attachment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsModified", DbType="Bit")]
		public System.Nullable<bool> IsModified
		{
			get
			{
				return this._IsModified;
			}
			set
			{
				if ((this._IsModified != value))
				{
					this._IsModified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this._DeletedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="NVarChar(256)")]
		public string DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this._DeletedBy = value;
				}
			}
		}
	}
	
	public partial class sp_FeedbackItemGetResult
	{
		
		private int _FeedbackItemID;
		
		private string _FeedbackItem;
		
		private string _FeedbackItemLocal;
		
		private string _FieldCaption;
		
		private System.Nullable<bool> _IsVisible;
		
		private System.Nullable<int> _DisplayOrder;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<bool> _IsModified;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<int> _PortalID;
		
		private string _AddedBy;
		
		private string _UpdatedBy;
		
		private string _DeletedBy;
		
		private string _CultureName;
		
		public sp_FeedbackItemGetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedbackItemID", DbType="Int NOT NULL")]
		public int FeedbackItemID
		{
			get
			{
				return this._FeedbackItemID;
			}
			set
			{
				if ((this._FeedbackItemID != value))
				{
					this._FeedbackItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedbackItem", DbType="NVarChar(256)")]
		public string FeedbackItem
		{
			get
			{
				return this._FeedbackItem;
			}
			set
			{
				if ((this._FeedbackItem != value))
				{
					this._FeedbackItem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedbackItemLocal", DbType="NVarChar(256)")]
		public string FeedbackItemLocal
		{
			get
			{
				return this._FeedbackItemLocal;
			}
			set
			{
				if ((this._FeedbackItemLocal != value))
				{
					this._FeedbackItemLocal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldCaption", DbType="NVarChar(500)")]
		public string FieldCaption
		{
			get
			{
				return this._FieldCaption;
			}
			set
			{
				if ((this._FieldCaption != value))
				{
					this._FieldCaption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVisible", DbType="Bit")]
		public System.Nullable<bool> IsVisible
		{
			get
			{
				return this._IsVisible;
			}
			set
			{
				if ((this._IsVisible != value))
				{
					this._IsVisible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayOrder", DbType="Int")]
		public System.Nullable<int> DisplayOrder
		{
			get
			{
				return this._DisplayOrder;
			}
			set
			{
				if ((this._DisplayOrder != value))
				{
					this._DisplayOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsModified", DbType="Bit")]
		public System.Nullable<bool> IsModified
		{
			get
			{
				return this._IsModified;
			}
			set
			{
				if ((this._IsModified != value))
				{
					this._IsModified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this._DeletedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="NVarChar(256)")]
		public string DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this._DeletedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CultureName", DbType="NVarChar(256)")]
		public string CultureName
		{
			get
			{
				return this._CultureName;
			}
			set
			{
				if ((this._CultureName != value))
				{
					this._CultureName = value;
				}
			}
		}
	}
	
	public partial class sp_FeedbackSettingValueListResult
	{
		
		private int _FeedbackSettingValueID;
		
		private string _SettingKey;
		
		private string _SettingValue;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<bool> _IsModified;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<int> _PortalID;
		
		private string _AddedBy;
		
		private string _UpdatedBy;
		
		private string _DeletedBy;
		
		public sp_FeedbackSettingValueListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedbackSettingValueID", DbType="Int NOT NULL")]
		public int FeedbackSettingValueID
		{
			get
			{
				return this._FeedbackSettingValueID;
			}
			set
			{
				if ((this._FeedbackSettingValueID != value))
				{
					this._FeedbackSettingValueID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettingKey", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string SettingKey
		{
			get
			{
				return this._SettingKey;
			}
			set
			{
				if ((this._SettingKey != value))
				{
					this._SettingKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettingValue", DbType="NVarChar(256)")]
		public string SettingValue
		{
			get
			{
				return this._SettingValue;
			}
			set
			{
				if ((this._SettingValue != value))
				{
					this._SettingValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsModified", DbType="Bit")]
		public System.Nullable<bool> IsModified
		{
			get
			{
				return this._IsModified;
			}
			set
			{
				if ((this._IsModified != value))
				{
					this._IsModified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this._DeletedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="NVarChar(256)")]
		public string DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this._DeletedBy = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
